services:
- type: pserv
  name: elasticsearch
  env: docker
  plan: standard
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
    sizeGB: 10
  envVars:
  - key: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"
  - key: discovery.type
    value: single-node
  - key: cluster.name
    value: elastic
